### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

### ISSUE THREAD

**Issue by katesaikishore** [multicaret/laravel-acquaintances#67]
```
➜  New git:(master) ✗ php artisan migrate
Migrating: 2021_08_23_104103_create_acquaintances_friendships_groups_table

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `friendship_id` bigint unsigned not null, `friend_type` varchar(255) not null, `friend_id` bigint unsigned not null, `group_id` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

I have tried everything still getting this error

**Comment by mkwsra** [comment]
Hi there, this is most likely because of your config file, please note that if you have an old version of the library installed with an old version of the config file, you just have to delete it and publish the config file of this library again.

As you can see the table names are in the configs:
![image](https://user-images.githubusercontent.com/1743919/130410145-997c651a-2ace-4865-a6ae-ed5a4ffec6ef.png)


If it didn't work please provide me with your Laravel version and let me dig more for you :)

**Comment by katesaikishore** [comment]
@mkwsra  Thanks, for this, I have cleared my cache and updated the library now this problem is solved! Now getting a new one! This problem has been solved by making `bigInteger` but again I am getting the error!

 `SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `interactions` add constraint `interactions_user_id_foreign` foreign key (`user_id`) references `sights` (`id`) on delete cascade on update cascade)`

**Comment by mkwsra** [comment]
You're welcome, then just make sure that your `id` column with 'users' migration file is the same type with the `user_id` column in the interactions table, do to so just check the `config/acquaintances.php` at this key: `interactions_user_id_fk_column_type` if its value is the same or not.

Happy coding

**Comment by katesaikishore** [comment]
Yes, It works. Thanks For your help
