### ISSUE TITLE
Laravel 9 support?

### ISSUE THREAD

**Issue by criting** [multicaret/laravel-acquaintances#82]
Do you plan to update the package to be compatible with Laravel 9?

**Comment by mkwsra** [comment]
Hi there,

Can you please specify if you mean to increment PHP version or if there is something specific you are asking for?

Because the basic installation is working just fine:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/1743919/154806090-e4107530-5000-4e74-9f09-647330a41807.png">


If you wish attache the error you are facing and I will do what's necessary.

Thanks for using the package!

**Comment by criting** [comment]
Hi.

I was just asking because in the readme it says "Supports Laravel 8".  If there aren't any bugs on Laravel 9, please update the readme and include that supports Laravel 9 as well.

**Comment by mkwsra** [comment]
I just updated the readme file, thanks for telling us.

Cheers

**Comment by Chlemdel** [comment]
Will this work with Laravel 10?
